### ISSUE TITLE
AstroTuxLauncher TMPFS issue

### ISSUE THREAD

**Issue by HoleInTheSeat** [ImKringle/Ptero-Things#18]
Running the atrotux ptero egg was failing due to not enought disk space when downloading depot downloader to `/tmp`

I fixed this by changing wings config to increase tmpfs to 10gb instead of 100mb. I think there may be a better solution of having the depotdownloader downloaded to a directory in the container rather than tmp, but I am not sure how to acheive that. I tried binding a host dir to /tmp in the container, but that didnt seem to work.

**Comment by ImKringle** [comment]
This is just how AstroTuxLauncher handles game downloads, there's a note stating a tmpfs increase is required in the README.
